### ISSUE TITLE
How to build and run this project?

### ISSUE THREAD

**Issue by shujaatak** [maxjoehnk/Mizer#13]
This project seems awesome but facing build issues. It would be awesome if you please mention required build and run steps.

I tried to build the rust project using "cargo run" but it failed in the middle. Also I tried to run the flutter project but the ui shows nothing.

**Comment by shujaatak** [comment]
OK, now I built and run the ui for Linux. The UI show up now. It asks for IP etc which I think has something to do with the rust code. Going to try to build the rust code again.

**Comment by shujaatak** [comment]
Build failed with following error:
```
Compiling image v0.23.13
error: failed to run custom build command for `avahi-sys v0.10.0`

Caused by:
  process didn't exit successfully: `/home/shujaat/Downloads/node-based-mizer/target/debug/build/avahi-sys-ef570fa012293e22/build-script-build` (exit code: 101)
  --- stdout
  cargo:rustc-link-lib=avahi-client
  cargo:rustc-link-lib=avahi-common

  --- stderr
  wrapper.h:1:10: fatal error: 'avahi-client/client.h' file not found
  wrapper.h:1:10: fatal error: 'avahi-client/client.h' file not found, err: true
  thread 'main' panicked at 'failed to generate bindings: ()', /home/shujaat/.cargo/registry/src/github.com-1ecc6299db9ec823/avahi-sys-0.10.0/build.rs:20:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by shujaatak** [comment]
Solved avahi error by installing the following packages:
```
sudo apt install llvm-dev libclang-dev clang
sudo apt-get install libavahi-client-dev
```

**Comment by shujaatak** [comment]
Solved GStreamer related issue by installing the following packages:
`sudo apt-get install libgstreamer1.0-0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-doc gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl gstreamer1.0-gtk3 gstreamer1.0-qt5 gstreamer1.0-pulseaudio`

**Comment by shujaatak** [comment]
Now getting this error:

```
error: failed to run custom build command for `mizer-grpc-api v0.1.0 (/home/shujaat/Downloads/node-based-mizer/api/grpc)`

Caused by:
  process didn't exit successfully: `/home/shujaat/Downloads/node-based-mizer/target/debug/build/mizer-grpc-api-1307ed4742794a27/build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=protos

  --- stderr
  thread 'main' panicked at 'protoc binary not found: cannot find binary path', /home/shujaat/.cargo/registry/src/github.com-1ecc6299db9ec823/protoc-2.18.1/src/lib.rs:203:17
```

Although I installed protoc using this:
```
PROTOC_ZIP=protoc-3.15.6-osx-x86_64.zip
curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v3.15.6/protoc-3.15.6-linux-x86_64.zip
sudo unzip -o $PROTOC_ZIP -d /usr/local bin/protoc
sudo unzip -o $PROTOC_ZIP -d /usr/local 'include/*'
rm -f $PROTOC_ZIP
```

**Comment by shujaatak** [comment]
Now I resolved the above protoc related issue by allowing permission to any user to run protoc using this command:
`sudo chmod a+rwX /usr/local/bin/protoc `

but now I get the following error which has something to do with protoc version:
```
error: failed to run custom build command for `mizer-grpc-api v0.1.0 (/home/shujaat/Downloads/node-based-mizer/api/grpc)`

Caused by:
  process didn't exit successfully: `/home/shujaat/Downloads/node-based-mizer/target/debug/build/mizer-grpc-api-1307ed4742794a27/build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=protos

  --- stderr
  thread 'main' panicked at 'protoc version: Custom { kind: Other, error: "failed to spawn `\"/usr/local/bin/protoc\" \"--version\"`: Exec format error (os error 8)" }', /home/shujaat/.cargo/git/checkouts/grpc-rust-ef3896fc3d196f91/99c8d18/protoc-rust-grpc/src/lib.rs:97:40
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Which version of **protoc** you are using?

**Comment by shujaatak** [comment]
Solved the above protoc related issue by completely removing previously installed protoc and reinstalled using the following steps:
```
# Make sure you grab the latest version
curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v3.15.6/protoc-3.15.6-linux-x86_64.zip

# Unzip
unzip protoc-3.15.6-linux-x86_64.zip -d protoc3

# Move protoc to /usr/local/bin/
sudo mv protoc3/bin/* /usr/local/bin/

# Move protoc3/include to /usr/local/include/
sudo mv protoc3/include/* /usr/local/include/

# Optional: change owner
sudo chwon $USER /usr/local/bin/protoc
sudo chwon -R $USER /usr/local/include/google
```

**Comment by shujaatak** [comment]
Now getting this error:
```
error: failed to run custom build command for `gstreamer-video-sys v0.9.1`

Caused by:
  process didn't exit successfully: `/home/shujaat/Downloads/node-based-mizer/target/debug/build/gstreamer-video-sys-c06fc93adcab1289/build-script-build` (exit code: 1)
  --- stdout
  cargo:rerun-if-env-changed=GSTREAMER_VIDEO_1.0_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=GSTREAMER_VIDEO_1.0_STATIC
  cargo:rerun-if-env-changed=GSTREAMER_VIDEO_1.0_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  `"pkg-config" "--libs" "--cflags" "gstreamer-video-1.0" "gstreamer-video-1.0 >= 1.14"` did not exit successfully: exit code: 1
  --- stderr
  Package gstreamer-video-1.0 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `gstreamer-video-1.0.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'gstreamer-video-1.0' found
  Package gstreamer-video-1.0 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `gstreamer-video-1.0.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'gstreamer-video-1.0' found
```

**Comment by shujaatak** [comment]
Solved the above issue using this:
`sudo apt install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
`

but now I get this error:
```
error: failed to run custom build command for `gstreamer-player-sys v0.9.1`

Caused by:
  process didn't exit successfully: `/home/shujaat/Downloads/node-based-mizer/target/debug/build/gstreamer-player-sys-17cb927216bbf260/build-script-build` (exit code: 1)
  --- stdout
  cargo:rerun-if-env-changed=GSTREAMER_PLAYER_1.0_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=GSTREAMER_PLAYER_1.0_STATIC
  cargo:rerun-if-env-changed=GSTREAMER_PLAYER_1.0_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  `"pkg-config" "--libs" "--cflags" "gstreamer-player-1.0" "gstreamer-player-1.0 >= 1.12"` did not exit successfully: exit code: 1
  --- stderr
  Package gstreamer-player-1.0 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `gstreamer-player-1.0.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'gstreamer-player-1.0' found
  Package gstreamer-player-1.0 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `gstreamer-player-1.0.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'gstreamer-player-1.0' found
```

**Comment by shujaatak** [comment]
Solved the above Gstreamer-player-1.0 related issue by installing the following package:
`sudo apt-get install libgstreamer-plugins-bad1.0-dev`

**Comment by shujaatak** [comment]
At last successfully built and run the project!

**Comment by maxjoehnk** [comment]
Congrats on getting the project to run.
Documentation wise this project definitely needs improvement, but I would like to get some features ready so I can actually use this before I start with user documentation.

The gstreamer dependency is going to be replaced soon(ish) as I want to replace it with a custom wgpu based rendering pipeline. This should reduce the native dependencies required to build this project.
The protoc and avahi dependencies will probably stay and should be documented.

Also when you go to the actions section of the repository you will find pre-compiled binaries of the ui and the service.
